Resources:
  BuildImageLambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: frontend-client-gateway-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: "cloudwatch-logs-config"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource: "arn:aws:logs:eu-central-1:648410456371:*"
          - Effect: Allow
            Action:
              - logs:PutLogEvents
              - logs:CreateLogStream
            Resource: "arn:aws:logs:eu-central-1:648410456371:log-group:/aws/lambda/frontend-ecs-services-dev-client:*"
      - PolicyName: "start-build-process"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - codebuild:StartBuild
            Resource: "arn:aws:codebuild:eu-central-1:648410456371:project/frontend-code-build-service"
      - PolicyName: "permissions-for-ddb"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Query
              Resource: "arn:aws:dynamodb:eu-central-1:648410456371:table/frontend-ddb-client"