Resources:
  FrontendCodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: frontend-code-build-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: "frontend-code-build-inline-policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: "*"
          - Effect: "Allow"
            Action:
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:GetObjectVersion"
            - "s3:ListBucket"
            Resource: "*"
          - Effect: "Allow"
            Action:
            - "ecr:BatchGetImage"
            - "ecr:BatchCheckLayerAvailability"
            - "ecr:CompleteLayerUpload"
            - "ecr:DescribeImages"
            - "ecr:DescribeRepositories"
            - "ecr:GetDownloadUrlForLayer"
            - "ecr:InitiateLayerUpload"
            - "ecr:ListImages"
            - "ecr:PutImage"
            - "ecr:UploadLayerPart"
            Resource: "arn:aws:ecr:eu-central-1:648410456371:repository/lazzaro-front-repo"
          - Effect: "Allow"
            Action:
            - "ecr:GetAuthorizationToken"
            Resource: "*"
          - Effect: "Allow"
            Action:
            - "secretsmanager:DescribeSecret"
            - "secretsmanager:PutSecretValue"
            - "secretsmanager:CreateSecret"
            - "secretsmanager:DeleteSecret"
            - "secretsmanager:CancelRotateSecret"
            - "secretsmanager:ListSecretVersionIds"
            - "secretsmanager:UpdateSecret"
            - "secretsmanager:GetResourcePolicy"
            - "secretsmanager:GetSecretValue"
            - "secretsmanager:RestoreSecret"
            - "secretsmanager:UpdateSecretVersionStage"
            - "secretsmanager:RotateSecret"
            Resource: "arn:aws:secretsmanager:eu-central-1:648410456371:secret:dockerToken-XYhC3a"