Resources:
  ClientTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: Client
          AttributeType: S
      KeySchema:
        - AttributeName: Client
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: frontend-ddb-client-${env:environment}
      Tags:
        - Key: "Name"
          Value: frontend-ddb-client-${env:environment}
        - Key: "Creation_Date"
          Value: "14 June 2021"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  StreamArn:
    Value: !GetAtt ClientTable.StreamArn